[package]
name = "shared_ownership_coordinator"
version = "0.1.0"
description = "A Holochain zome module for having multiple agents share ownership of any entry"

rust-version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
serde.workspace = true
hdk.workspace = true

zome_utils = {path = "../../crates/zome_utils" }
zome_signals = {path = "../../crates/zome_signals" }
zome_path = {path = "../../crates/zome_path" }

shared_ownership_integrity = {path = "../shared_ownership_integrity" }

bincode = "1.3"

