[package]
name = "time_indexing"
version = "0.2.0"
description = "A time-based indexing solution for Holochain zome data."

rust-version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
serde.workspace = true
holochain_serialized_bytes.workspace = true
hdk.workspace = true

zome_path = { path = "../zome_path" }

#base64 = {version = "0.13"}
chrono = { version = "0.4.22", default-features = false, features = ["clock", "std", "oldtime", "serde"] }
