[package]
name = "path_explorer"
version = "0.1.0"
description = "A Holochain coordinator zome module for exploring all Paths available in a DHT."

rust-version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
serde.workspace = true
hdk.workspace = true

zome_utils = {path = "../../crates/zome_utils" }
zome_path = {path = "../../crates/zome_path" }

#time_indexing = {path = "../../crates/time_indexing" }

path_explorer_types = {path = "../path_explorer_types" }
