[package]
name = "zome_signals"
version = "0.1.0"
description = "A foundation layer for a signal-based architecture for Holochain applications."

rust-version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
holochain_serialized_bytes.workspace = true
serde.workspace = true
hdk.workspace = true
