[package]
name = "profiles_alt_coordinator"
version = "0.2.0"
description = "Alternate coordinator zome for the Profiles zome."

rust-version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
hdk.workspace = true
hc_zome_profiles_integrity.workspace = true

zome_utils = { path = "../../crates/zome_utils" }
zome_signals = { path = "../../crates/zome_signals" }
zome_core = { path = "../zome_core" }




